// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYj72cuLeDuLVydu0gtYTN0BAjro8tM3Y',
    appId: '1:615560682112:web:d9a4522da17905b4df2465',
    messagingSenderId: '615560682112',
    projectId: 'toffeebackend',
    authDomain: 'toffeebackend.firebaseapp.com',
    storageBucket: 'toffeebackend.firebasestorage.app',
    measurementId: 'G-S2MREQ5SF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzDaqenlw9WtVarU-lehZmtAcVTc_jKEg',
    appId: '1:615560682112:android:d0040ee5e12baae4df2465',
    messagingSenderId: '615560682112',
    projectId: 'toffeebackend',
    storageBucket: 'toffeebackend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTwAa6-stzO8XAySDB7yNI6jMYSjjx_9E',
    appId: '1:615560682112:ios:90ecb84511c259cedf2465',
    messagingSenderId: '615560682112',
    projectId: 'toffeebackend',
    storageBucket: 'toffeebackend.firebasestorage.app',
    iosBundleId: 'com.toffee.toffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTwAa6-stzO8XAySDB7yNI6jMYSjjx_9E',
    appId: '1:615560682112:ios:90ecb84511c259cedf2465',
    messagingSenderId: '615560682112',
    projectId: 'toffeebackend',
    storageBucket: 'toffeebackend.firebasestorage.app',
    iosBundleId: 'com.toffee.toffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYj72cuLeDuLVydu0gtYTN0BAjro8tM3Y',
    appId: '1:615560682112:web:062cdde1216750a3df2465',
    messagingSenderId: '615560682112',
    projectId: 'toffeebackend',
    authDomain: 'toffeebackend.firebaseapp.com',
    storageBucket: 'toffeebackend.firebasestorage.app',
    measurementId: 'G-F6B6SEFC66',
  );
}
